### PR TITLE
Policysigned - Add new policy tool

### PR DESCRIPTION
**Pull request by idesai**

### CODE REVIEW

**Comment by idesai** [comment]
> make sure your updating the CHANGELOG for each tool you add

Thanks @williamcroberts. Will do.

**Comment by idesai** [comment]
> You don't use the nonceTPM output, so why create the option?

It is to be used in the policysigned and policysecret

**Comment by williamcroberts** [comment]
> > You don't use the nonceTPM output, so why create the option?
> 
> It is to be used in the policysigned and policysecret

I didn't see any test that uses it, where is it?

**Comment by idesai** [comment]
> > > You don't use the nonceTPM output, so why create the option?
> > 
> > 
> > It is to be used in the policysigned and policysecret
> 
> I didn't see any test that uses it, where is it?

Ah I see the confusion :), In the works. I will start using the draft PR feature.

**Comment by williamcroberts** [comment]
> > > > You don't use the nonceTPM output, so why create the option?
> > > 
> > > 
> > > It is to be used in the policysigned and policysecret
> > 
> > 
> > I didn't see any test that uses it, where is it?
> 
> Ah I see the confusion :), In the works. I will start using the draft PR feature.

Yeah when you introduce a feature, you need to introduce a consumer at the same time.

**Pull request merged**
