### PR TITLE
cirrus: switch tss back to master branch

### PR DESCRIPTION
**Pull request by tstruk**

### CODE REVIEW

**Comment by williamcroberts** [comment]
@tstruk the commit message is missing why? Why are switching back to master?

**Comment by tstruk** [comment]
> @tstruk the commit message is missing why? Why are switching back to master?

That's a revert of https://github.com/tpm2-software/tpm2-tools/commit/03bfaff34bcc2497e140487498b791d93607da30
which was a temporary change.

**Comment by williamcroberts** [comment]
> > @tstruk the commit message is missing why? Why are switching back to master?
> 
> That's a revert of [03bfaff](https://github.com/tpm2-software/tpm2-tools/commit/03bfaff34bcc2497e140487498b791d93607da30)
> which was a temporary change.

Okay, Should we pull it even though cirrus is still failing for tpm2-tools?

**Comment by tstruk** [comment]
> > > @tstruk the commit message is missing why? Why are switching back to master?
> > 
> > 
> > That's a revert of [03bfaff](https://github.com/tpm2-software/tpm2-tools/commit/03bfaff34bcc2497e140487498b791d93607da30)
> > which was a temporary change.
> 
> Okay, Should we pull it even though cirrus is still failing for tpm2-tools?

It's still running https://cirrus-ci.com/task/5788595732611072
I tested it locally and it's fine, but please wait till it finishes on cirrus.

**Comment by tstruk** [comment]
> I tested it locally and it's fine, but please wait till it finishes on cirrus.

I think it's safe to merge this one in

**Pull request merged**
