### PR TITLE
Update example tpm2_policyauthorize.1.md

### PR DESCRIPTION
**Pull request by ernesto418**
The example was bad explained because in the trial session the authorization policy is being created, it is not authorizing anything (you don't need to include -i pcr.policy in the trial session)
So I changed that, restructured the example, and changed the example variables names to make this command more understandable

### CODE REVIEW

**Comment by idesai** [comment]
:thinking: can you try `git commit --amend -s`

**Comment by ernesto418** [comment]
I verified the commit's signing key. Is it ok now?

**Comment by josephlr** [comment]
@ernesto418 it looks like your commit is missing a [DCO](https://wiki.linuxfoundation.org/dco). To fix, run
```
git commit --amend --no-edit --signoff
```
and then repush the commit (see the CI failure for more info).

**Comment by ernesto418** [comment]
Ok thanks @josephlr and @idesai

**Pull request merged**
