### PR TITLE
Implement tpm2_nvincrement

### PR DESCRIPTION
**Pull request by GlovePuppet**
Implemented tpm2_nvincrement, a copy/paste/rename from tpm2_nvwrite

I have noticed that the increments do not behave as I would have expected, perhaps I am missing something?

Tested against Infineon TPM9670

$ tpm2_clear

$ tpm2_nvdefine -x 0x1500001 -a o -s 8 -t "ownerread|ownerwrite|nt=1"
$ tpm2_nvdefine -x 0x1500002 -a o -s 8 -t "ownerread|ownerwrite|nt=1"
$ tpm2_nvdefine -x 0x1500003 -a o -s 8 -t "ownerread|ownerwrite|nt=1"

$ tpm2_nvincrement -x 0x1500001 -a o 
$ tpm2_nvread -x 0x1500001 -a o -s 8 | hexdump -C
00000000  00 00 00 00 00 00 00 03                           |........|

$ tpm2_nvincrement -x 0x1500002 -a o 
$ tpm2_nvread -x 0x1500002 -a o -s 8 | hexdump -C
00000000  00 00 00 00 00 00 00 04                           |........|

$ tpm2_nvincrement -x 0x1500003 -a o
$ tpm2_nvread -x 0x1500003 -a o -s 8 | hexdump -C
00000000  00 00 00 00 00 00 00 05                           |........|

$ tpm2_nvlist
0x1500001:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ownerwrite|nt=0x1|ownerread|written
    value: 0x12000220
  size: 8

0x1500002:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ownerwrite|nt=0x1|ownerread|written
    value: 0x12000220
  size: 8

0x1500003:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ownerwrite|nt=0x1|ownerread|written
    value: 0x12000220
  size: 8

### CODE REVIEW

**Comment by GlovePuppet** [comment]
Some more testing, run against the IBM simulator

```
#!/bin/bash

source tpm2-tools/test/integration/helpers.sh
start_up

alg_pcr_policy=sha1
pcr_ids="0,1,2,3"
file_pcr_value=pcr.bin
file_policy=policy.data

tpm2_clear
tpm2_nvdefine -x 0x1500018 -a o -s 8 -t "ownerread|policywrite|ownerwrite|nt=1"
tpm2_nvincrement -x 0x1500018 -a o 
tpm2_nvread -x 0x1500018 -a o -s 8 | hexdump -C               # 00000000  00 00 00 00 00 00 00 01
tpm2_nvrelease -x 0x1500018 -a o

tpm2_pcrlist -L ${alg_pcr_policy}:${pcr_ids} -o $file_pcr_value
tpm2_createpolicy -P -L ${alg_pcr_policy}:${pcr_ids} -F $file_pcr_value -f $file_policy
tpm2_nvdefine -x 0x1500016 -a 0x40000001 -s 8 -L $file_policy -t "policyread|policywrite|nt=1"
tpm2_nvincrement -x 0x1500016 -a 0x1500016 -L ${alg_pcr_policy}:${pcr_ids} -F $file_pcr_value
tpm2_nvread -x 0x1500016 -a 0x1500016 -L ${alg_pcr_policy}:${pcr_ids} -F $file_pcr_value -s 8 | hexdump -C       # 00000000  00 00 00 00 00 00 00 02
```

It seems strange that the first counter (index 0x1500018) has the value 1 whereas the second counter (index 0x1500016) has the value 2.

**Comment by williamcroberts** [comment]
> It seems strange that the first counter (index 0x1500018) has the value 1 whereas the second counter (index 0x1500016) has the value 2.

That does seem incredibly strange.

**Comment by GlovePuppet** [comment]
More testing on the Infineon 9670

```
# Reset the TPM, check nothing is defined
$ tpm2_clear
$ tpm2_nvlist 
0x1c00002:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1200762
  size: 1184

0x1c0000a:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1200762
  size: 787

# Define a counter
$ tpm2_nvdefine -x 0x1500018 -a o -s 8 -t "ownerread|policywrite|ownerwrite|nt=1"

# Can't read until written/incremented
$ tpm2_nvread -x 0x1500018 -a o -s 8 | hexdump -C
WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:325:Esys_NV_Read_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:115:Esys_NV_Read() Esys Finish ErrorCode (0x0000014a) 
ERROR: Failed to read NVRAM area at index 0x1500018
ERROR: Esys_NV_Read(0x14A) - tpm:error(2.0): an NV Index is used before being initialized or the state saved by TPM2_Shutdown(STATE) could not be restored
ERROR: Unable to run tpm2_nvread

# No written flag
$ tpm2_nvlist
0x1500018:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ownerwrite|policywrite|nt=0x1|ownerread
    value: 0x1A000200
  size: 8

0x1c00002:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1200762
  size: 1184

0x1c0000a:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1200762
  size: 787

# Increment and read counter (value has persisted since last test run)
$ tpm2_nvincrement -x 0x1500018 -a o 
$ tpm2_nvread -x 0x1500018 -a o -s 8 | hexdump -C
00000000  00 00 00 00 00 00 00 07                           |........|
00000008

# Release it & check it really has gone
$ tpm2_nvrelease -x 0x1500018 -a o
$ tpm2_nvread -x 0x1500018 -a o -s 8 | hexdump -C
WARNING:esys:src/tss2-esys/api/Esys_NV_ReadPublic.c:306:Esys_NV_ReadPublic_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/esys_tr.c:201:Esys_TR_FromTPMPublic_Finish() Error NV_ReadPublic ErrorCode (0x0000018b) 
ERROR:esys:src/tss2-esys/esys_tr.c:309:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x0000018b) 
ERROR: Esys_TR_FromTPMPublic(0x18B) - tpm:handle(1):the handle is not correct for the use
ERROR:esys:src/tss2-esys/esys_tr.c:345:Esys_TR_Close() Error: Esys handle does not exist (70018). 
ERROR: Esys_NV_ReadPublic(0x70018) - fapi:0x18
ERROR: Unable to run tpm2_nvread
$ tpm2_nvlist
0x1c00002:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1200762
  size: 1184

0x1c0000a:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1200762
  size: 787

$ tpm2_nvincrement -x 0x1500018 -a o 
WARNING:esys:src/tss2-esys/api/Esys_NV_ReadPublic.c:306:Esys_NV_ReadPublic_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/esys_tr.c:201:Esys_TR_FromTPMPublic_Finish() Error NV_ReadPublic ErrorCode (0x0000018b) 
ERROR:esys:src/tss2-esys/esys_tr.c:309:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x0000018b) 
ERROR: Esys_TR_FromTPMPublic(0x18B) - tpm:handle(1):the handle is not correct for the use
ERROR: Unable to run tpm2_nvincrement

# Create counter again
$ tpm2_nvdefine -x 0x1500018 -a o -s 8 -t "ownerread|policywrite|ownerwrite|nt=1"
$ tpm2_nvlist
0x1500018:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ownerwrite|policywrite|nt=0x1|ownerread
    value: 0x1A000200
  size: 8

0x1c00002:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1200762
  size: 1184

0x1c0000a:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1200762
  size: 787

# Increment, read and check value has persisted
$ tpm2_nvincrement -x 0x1500018 -a o 
$ tpm2_nvread -x 0x1500018 -a o -s 8 | hexdump -C
00000000  00 00 00 00 00 00 00 08                           |........|

```

**Comment by williamcroberts** [comment]
Per the Architecture [spec](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf) it uses the biggest counter value ever seen as its initializer value.
```37.2.6.3 NV Counter Index
When an Index has the TPMA_NV_COUNTER attribute, it behaves as a monotonic counter and may only
be modified using TPM2_NV_Increment().
When an NV counter is created, it has no value and the TPMA_NV_WRITTEN attribute will be CLEAR.
On each TPM2_NV_Increment() the TPM checks the TPMA_NV_WRITTEN attribute of the Index. If it is
CLEAR, then the TPM will initialize the 8-octet counter value with the TPM’s largest NV Counter Index
value. This value is required to be the largest count held by any NV Counter over the lifetime of the TPM.
The TPMA_NV_WRITTEN attribute will be SET.
```

**Comment by GlovePuppet** [comment]
Then it's not strange at all :)

What do I do about the failing Travis builds? I don't think it's my changes causing whatever that failure is

**Comment by williamcroberts** [comment]
> Then it's not strange at all :)
> 
> What do I do about the failing Travis builds? I don't think it's my changes causing whatever that failure is

```
  File "scripts/utils/analyze.py", line 326, in <module>
    main()
  File "scripts/utils/analyze.py", line 317, in main
    conflictor = ToolConflictor(tools, full=args.custom)
  File "scripts/utils/analyze.py", line 210, in __init__
    sys.exit("Did not find group for tool: %s", tool.name)
TypeError: exit expected at most 1 arguments, got 2
```
This incredibly ~~clear~~ convoluted dump means your tools wasn't in the list of known tools.

Look at this PR https://github.com/tpm2-software/tpm2-tools/pull/1337 and that author scripts/utils/analyze.py to add the tool to the known set. This would go in the group name (gname) nv on https://github.com/lestums/tpm2-tools/blob/a4b3321d5523913c04a76d26c236759fb0eba124/scripts/utils/analyze.py#L157.

That script helps us track what wonky things are going on with the options in the tools as we march towards correcting them for the 4.0 release. At 4.0 release we will provide backwards compatible options moving forward.

**Pull request merged**
