### PR TITLE
tss2: Account for changes TPMA_* macros in upstream headers.

### PR DESCRIPTION
**Pull request by flihp**
Signed-off-by: Philip Tricca <philip.b.tricca@intel.com>

### CODE REVIEW

**Comment by flihp** [comment]
strange, error messages are all related to dbus activation (dbus trying to launch an instance of the tabrmd). I'm assuming this isn't intentional ...

**Comment by liuqun** [comment]
@flihp Maybe the error is cause since we rename libtcti_socket.so to libtcti_mssim.so. And tpm2-abrmd failed to access libtcti_socket.so

**Comment by flihp** [comment]
thanks @liuqun, lots of churn to keep up with these last few weeks. Will have this building again in a bit.

**Comment by flihp** [comment]
looks like I b0rked up the default config string for the mssim TCTI upstream

**Pull request merged**
