### PR TITLE
Fixing command option typo

### PR DESCRIPTION
**Pull request by tatac1**
Some of command options are wrong.

### CODE REVIEW

**Comment by idesai** [comment]
@tatac1 please signoff on the commit and push again "git commit --amend --signoff"

**Comment by tatac1** [comment]
> @tatac1 please signoff on the commit and push again "git commit --amend --signoff"

I did `git commit --amend --signoff` and have pushed.

**Comment by idesai** [comment]
@tatac1, there are some intermediate commits that can be rebased. Can you please. Thanks!

git rebase HEAD~3

**Comment by idesai** [comment]
@tatac1  Closing in lieu of #1940

**Pull request closed without merging**
