### PR TITLE
ci: Have travis install libgcrypt dev package.

### PR DESCRIPTION
**Pull request by flihp**
This is a new dependency from the addition of the ESAPI library to
tpm2-tss.

Signed-off-by: Philip Tricca <philip.b.tricca@intel.com>

### CODE REVIEW

**Comment by flihp** [comment]
Ugh. I hadn't even considered this but it looks like the travis image won't install gcrypt dev packages and the openssl dev packages at the same time? Not sure this is really what's happening but from my first pass over the build output it looks like it may be.

**Comment by flihp** [comment]
that's not it, the build is complaining about not being able to install `librtmp-dev` which is required by `libcurl4-openssl-dev`

**Comment by flihp** [comment]
```
The following packages have unmet dependencies:
 libgcrypt20-dev : Conflicts: libgcrypt-dev
                   Conflicts: libgcrypt11-dev but 1.5.3-2ubuntu4.5 is to be installed
```

**Comment by flihp** [comment]
looks like this issue: https://launchpad.net/ubuntu/+source/libgcrypt20/1.6.1-2 which oddly isn't an issue in the tpm2-tss and tpm2-abrmd builds. All evidence points to the VM travis image being the issue since the two other projects are using the container build.

Might be able to work around this by doing some `sudo apt-get` stuff in `before_install`. Alternatively it may be time to bite the bullet and port the travis-ci stuff over to the container build.

**Comment by dantpm** [comment]
There may be a hysterical reason for it, but it’s unusual to need both as they provide similar functionality.

Perhaps the test suite needs openssl and the tpm2 software needs gcrypt?

Gcrypt is a lot more buggy than OpenSSL, but sometimes gcrypt is used because of the GNU license.

Dan

**Comment by flihp** [comment]
This is fun: manually removing libgcrypt11-dev causes apt to remove libcurl4-openssl-dev. Definitely the right thing to do.

**Comment by flihp** [comment]
This was an exercise in futility. See #900.

**Pull request closed without merging**
