### PR TITLE
tss2 * tools: Fix for fapi-branch-select

### PR DESCRIPTION
**Pull request by cplappert**
This PR fixes two issues with the tss2 * tools:

1. tss2 *: Fix integration test fapi-branch-select: With the new TSS version also PolicyRef is included into the search for valid policies. Thus, the test is adapted to include PolicyRef in the authorization policy. This should fix the errors in PR tpm2-software#2264.

2. tss2 *: Fix parameter in provision test: The provision test still had an outdated parameter.

Signed-off-by: Christian Plappert <christian.plappert@sit.fraunhofer.de>

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
Just to make the situation clear:
tpm2-tss fixed a bug.
That fix revels this bug in the tools tests.

**Comment by williamcroberts** [comment]
> Just to make the situation clear:
> tpm2-tss fixed a bug.
> That fix revels this bug in the tools tests.

@AndreasFuchsSIT what bug/commit in tpm2-tss are you referring to? I ask just for crosslinking between the projects so we know what changed over there for archival purposes.

**Comment by AndreasFuchsSIT** [comment]
Sorry, it's this commit: https://github.com/tpm2-software/tpm2-tss/commit/419b48e190be8eb0ac24c8e084662c0420330167 coming from this PR: https://github.com/tpm2-software/tpm2-tss/pull/1875

**Comment by AndreasFuchsSIT** [comment]
@williamcroberts @idesai Could you get this and the backports merged please ? It's a blocker for some use cases.

**Pull request merged**
