### PR TITLE
ci: enable multi-arch builds

### PR DESCRIPTION
**Pull request by williamcroberts**
Signed-off-by: William Roberts <william.c.roberts@intel.com>

### CODE REVIEW

**Comment by williamcroberts** [comment]
timeout, we might need to do a more compact build/test run on emulated architectures.

**Comment by idesai** [comment]
> timeout, we might need to do a more compact build/test run on emulated architectures.

@williamcroberts, should only a successful build suffice?

**Comment by williamcroberts** [comment]
> > timeout, we might need to do a more compact build/test run on emulated architectures.
> 
> @williamcroberts, should only a successful build suffice?

yes

**Comment by malikabhi05** [comment]
@williamcroberts @idesai does "make distcheck" [here](https://github.com/tpm2-software/tpm2-tools/blob/0f11c70f70fe846cef8fe7fed93a66f205fd0e9b/.ci/docker.run#L58) force the documentation to be generated? I was expecting it to not generate documentation if pandoc isn't present, however, it errors out saying `You do not have pandoc, a requirement for the distribution of manpages`.

Can I replace make distcheck and make distclean with make -jN for multiarch builds or does that cause material problems for the build? :)

**Comment by williamcroberts** [comment]
> @williamcroberts @idesai does "make distcheck" [here](https://github.com/tpm2-software/tpm2-tools/blob/0f11c70f70fe846cef8fe7fed93a66f205fd0e9b/.ci/docker.run#L58) force the documentation to be generated? I was expecting the build to not generate documentation if pandoc isn't present, however, the build errors out saying `You do not have pandoc, a requirement for the distribution of manpages`.
> 
> Can I replace make distcheck and make distclean with make -jN for multiarch builds or does that cause material problems for the build? :)

Yes distcheck requires pandoc as it's a dist sub-command and to make the distribution tarball you need pandoc.

**Comment by malikabhi05** [comment]
> Yes distcheck requires pandoc as it's a dist sub-command and to make the distribution tarball you need pandoc.

I'm removing pandoc from the build in order to speed it up as it is currently timing out. Please let me know if I can use make -jN instead of make distcheck for multiarch builds?

**Comment by williamcroberts** [comment]
> > Yes distcheck requires pandoc as it's a dist sub-command and to make the distribution tarball you need pandoc.
> 
> I'm removing pandoc from the build in order to speed it up as it is currently timing out. Please let me know if I can use make -jN instead of make distcheck for multiarch builds?

Yeah that would work.

**Comment by malikabhi05** [comment]
The build is now failing due to integration tests [here](https://github.com/malikabhi05/tpm2-tools/blob/1b940000536268059e46dd82e5d3e80f840a1481/.ci/docker.run#L95). I keep on seeing the error `Could not start simulator at port`. Do the integration tests have to be run for multiarch builds?

This is the [log](https://github.com/malikabhi05/tpm2-tools/runs/6782655709?check_suite_focus=true)

**Comment by idesai** [comment]
Tracking this in #3110

**Pull request closed without merging**
