### PR TITLE
fix typing

### PR DESCRIPTION
**Pull request by droccom**
Fixed a type issue which causes build failure on my platform.

### CODE REVIEW

**Comment by williamcroberts** [comment]
> Fixed a type issue which causes build failure on my platform.

Whats the actual error? I wonder why that callback function prototype is not matching up, I think the cast is hiding the actual issue.

**Comment by droccom** [comment]
```console
  CC       tools/fapi/tss2-tss2_template.o
tools/fapi/tss2_template.c: In function 'main':
tools/fapi/tss2_template.c:517:31: error: passing argument 2 of 'Fapi_SetSignCB' from incompatible pointer type [-Werror=incompatible-pointer-types]
  517 |     r = Fapi_SetSignCB (fctx, sign_callback, NULL);
      |                               ^~~~~~~~~~~~~
      |                               |
      |                               TSS2_RC (*)(const char *, const char *, const char *, const char *, uint32_t,  const uint8_t *, size_t,  const uint8_t **, size_t *, void *) {aka unsigned int (*)(const char *, const char *, const char *, const char *, unsigned int,  const unsigned char *, long unsigned int,  const unsigned char **, long unsigned int *, void *)}
In file included from ./tools/fapi/tss2_template.h:6,
                 from tools/fapi/tss2_template.c:22:
/usr/include/tss2/tss2_fapi.h:693:21: note: expected 'Fapi_CB_Sign' {aka 'unsigned int (*)(FAPI_CONTEXT *, const char *, const char *, const char *, unsigned int,  const unsigned char *, long unsigned int,  unsigned char **, long unsigned int *, void *)'} but argument is of type 'TSS2_RC (*)(const char *, const char *, const char *, const char *, uint32_t,  const uint8_t *, size_t,  const uint8_t **, size_t *, void *)' {aka 'unsigned int (*)(const char *, const char *, const char *, const char *, unsigned int,  const unsigned char *, long unsigned int,  const unsigned char **, long unsigned int *, void *)'}
  693 |     Fapi_CB_Sign    callback,
      |     ~~~~~~~~~~~~~~~~^~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by williamcroberts** [comment]
There is the problem. The API changed in tpm2-tss commit https://github.com/tpm2-software/tpm2-tss/commit/e0636dd6fbec4f286cc908117ecef4d820a50f79 for the callback API. So the old and new callbacks have differing signatures. The old one took a FAPI_CONTEXT * the newer one takes an object path.

So I think we either need to handle the old and new interfaces or set the tss2 tools high enough to avoid this problem. @AndreasFuchsSIT and @cplappert how do you want to proceed?

**Comment by williamcroberts** [comment]
@droccom I think you can just upgrade your tpm2-tss version to 3.0.0 and it should correct this. What version is your tpm2-tss library right now?

**Comment by droccom** [comment]
@williamcroberts I am using the latest from `master`. Here follows a Dockerfile you can use to replicate:

```Dockerfile
FROM fedora:32

RUN dnf -y update && dnf install -y \
        git autoconf automake libtool

RUN dnf -y install autoconf-archive tpm2-tss-devel uuid-devel libuuid-devel
RUN git clone https://github.com/tpm2-software/tpm2-tools.git
WORKDIR tpm2-tools
RUN git checkout master
RUN ./bootstrap
RUN ./configure
RUN make
```

**Comment by williamcroberts** [comment]
> I am using the latest from `master`. Here follows a Dockerfile you can use to replicate:

tools are on master, but your tss isn't. You're tss is on 2.4.4 which is causing the issue. So we need a fix that detects the old version of FAPI and has a callback for that version. @AndreasFuchsSIT and @cplappert on any help on this one?

```bash
dnf info tpm2-tss-devel
Last metadata expiration check: 0:00:14 ago on Mon Dec 21 15:38:47 2020.
Available Packages
Name         : tpm2-tss-devel
Version      : 2.4.4
Release      : 1.fc32
Architecture : i686
Size         : 305 k
Source       : tpm2-tss-2.4.4-1.fc32.src.rpm
Repository   : updates
Summary      : Headers and libraries for building apps that use tpm2-tss
URL          : https://github.com/tpm2-software/tpm2-tss
License      : BSD and TCGL
Description  : This package contains headers and libraries required to build applications that
             : use tpm2-tss.

Name         : tpm2-tss-devel
Version      : 2.4.4
Release      : 1.fc32
Architecture : x86_64
Size         : 305 k
Source       : tpm2-tss-2.4.4-1.fc32.src.rpm
Repository   : updates
Summary      : Headers and libraries for building apps that use tpm2-tss
URL          : https://github.com/tpm2-software/tpm2-tss
License      : BSD and TCGL
Description  : This package contains headers and libraries required to build applications that
             : use tpm2-tss.
```

**Comment by williamcroberts** [comment]
Untested, but compiles, but a patch like this is what we need to fix it:
```diff
diff --git a/tools/fapi/tss2_template.c b/tools/fapi/tss2_template.c
index 0e68bea6c4e5..a52efecc005c 100644
--- a/tools/fapi/tss2_template.c
+++ b/tools/fapi/tss2_template.c
@@ -256,7 +256,11 @@ TSS2_RC auth_callback(
 uint8_t *input_signature = NULL;
 
 TSS2_RC sign_callback(
+#ifdef FAPI_3_0
     char        const *objectPath,
+#else /* FAPI_3_0 */
+    __attribute__((unused)) FAPI_CONTEXT *fapi_context,
+#endif /* FAPI_3_0 */
     char        const *description,
     char        const *publicKey,
     char        const *publicKeyHint,
@@ -312,10 +316,15 @@ TSS2_RC sign_callback(
                 return TSS2_FAPI_RC_GENERAL_FAILURE;
             }
         }
-
+#ifdef FAPI_3_0
         printf("%s: Authorize usage of %s by signing the nonce with %s the hash "\
             "algorithm \"%s\".\n", description, objectPath, publicKeyHintStr,
             hashAlgName);
+#else
+        printf("%s: Authorize usage of the key by signing the nonce with %s the hash "\
+            "algorithm \"%s\".\n", description, publicKeyHintStr,
+            hashAlgName);
+#endif
 
     }
     printf("Filename for nonce output: ");
```

**Comment by droccom** [comment]
@williamcroberts sorry I misread (tools for tss), I will test both your patch (with 2.4.4) and with 3.0. Thanks!

**Comment by droccom** [comment]
@williamcroberts following up my tests:

- upgrading `tpm2-tss` to `3.0.x` works
- keeping `tpm2-tss` at version 2 (i.e. shipped by the `tpm2-tss-devel` package on Fedora 32) and applying the patch you posted, I am still getting the same error

**Comment by williamcroberts** [comment]
> @williamcroberts following up my tests:
> 
> * upgrading `tpm2-tss` to `3.0.x` works
> * keeping `tpm2-tss` at version 2 (i.e. shipped by the `tpm2-tss-devel` package on Fedora 32) and applying the patch you posted, I am still getting the same error

Did you re-run configure when you built the tools against tpm2-tss 2.X? What's the lib/config.h look like, specifically the define for ESYS_3_0?

It should be defined causing us to take the else.
```C
/* Esys3.0 */
#define ESYS_3_0 1
```

**Comment by droccom** [comment]
I did reconfigure, but:

```console
tpm2-tools]# grep ESYS lib/config.h
#define ESYS_2_3 1
/* #undef ESYS_3_0 */
```

**Comment by williamcroberts** [comment]
> I did reconfigure, but:
> 
> ```
> tpm2-tools]# grep ESYS lib/config.h
> #define ESYS_2_3 1
> /* #undef ESYS_3_0 */
> ```

Hrmmm, what does:
```bash
pkg-config --modversion tss2-esys
```

return? That's where it pulls that info.

When you reconfigured and presumably installed tpm2-tss 3.X over 2.X, and built tpm2-tools, did you do a make distclean?

**Comment by droccom** [comment]
> Hrmmm, what does:
> 
> ```shell
> pkg-config --modversion tss2-esys
> ```
> 
> return? That's where it pulls that info.

```console
tpm2-tools]# pkg-config --modversion tss2-esys
2.4.4
```

> When you reconfigured and presumably installed tpm2-tss 3.X over 2.X, and built tpm2-tools, did you do a make distclean?

Of course I am doing the different tests in isolation (i.e. docker), no risk of conflicts here. For double-checking, I am attaching:
- your patch file
- the Dockerfile to reproduce
- the logs I see

[tpm2-tools.zip](https://github.com/tpm2-software/tpm2-tools/files/5742195/tpm2-tools.zip)

**Comment by cplappert** [comment]
This patch works for me. It is almost identical to williamcroberts' patch but
I noticed that also the signature parameter changed in the API (`const`). 

@droccom: Could you please give feedback if this works for you. Then I will make a PR
with this patch.

```diff
diff --git a/tools/fapi/tss2_template.c b/tools/fapi/tss2_template.c
index 0e68bea6..ecec0f04 100644
--- a/tools/fapi/tss2_template.c
+++ b/tools/fapi/tss2_template.c
@@ -256,14 +256,22 @@ TSS2_RC auth_callback(
 uint8_t *input_signature = NULL;
 
 TSS2_RC sign_callback(
+#ifdef FAPI_3_0
     char        const *objectPath,
+#else /* FAPI_3_0 */
+    __attribute__((unused)) FAPI_CONTEXT *fapi_context,
+#endif /* FAPI_3_0 */
     char        const *description,
     char        const *publicKey,
     char        const *publicKeyHint,
     uint32_t    hashAlg,
     uint8_t     const *dataToSign,
     size_t      dataToSignSize,
+#ifdef FAPI_3_0
     uint8_t     const **signature,
+#else /* FAPI_3_0 */
+    uint8_t     **signature,
+#endif /* FAPI_3_0 */
     size_t      *signatureSize,
     void        *userData)
 {
@@ -313,9 +321,15 @@ TSS2_RC sign_callback(
             }
         }
 
+#ifdef FAPI_3_0
         printf("%s: Authorize usage of %s by signing the nonce with %s the hash "\
             "algorithm \"%s\".\n", description, objectPath, publicKeyHintStr,
             hashAlgName);
+#else /* FAPI_3_0 */
+        printf("%s: Authorize usage of the key by signing the nonce with %s the "\
+            "hash algorithm \"%s\".\n", description, publicKeyHintStr,
+            hashAlgName);
+#endif /* FAPI_3_0 */
 
     }
     printf("Filename for nonce output: ");
```

**Comment by droccom** [comment]
@cplappert this patch works for me!

**Comment by cplappert** [comment]
Thank you for your feedback.
This issue is addressed in #2289.

**Comment by williamcroberts** [comment]
> Thank you for your feedback.
> This issue is addressed in #2289.

Thanks #2289 was merged so closing.

**Pull request closed without merging**
