### PR TITLE
Bugfix: tpm2_createek tool auto-save context used incorrect path

### PR DESCRIPTION
**Pull request by jetwhiz**
In the latest version of tpm2_createek, it appears that saving the context for non-persistent handles is not targeting the correct variable.  

According to the documentation, the "-c" option, which sets `ctx.ctx_obj.path`, specifies the context output file to use or "ek.ctx" if none is given.  The current implementation, however, will use `ctx.out_file_path` (set by "-p") which is supposed to be the public key output file.  This PR is designed to correct this.

### CODE REVIEW

**Comment by williamcroberts** [comment]
I think this is more of a documentation fix. The tools shouldn't be producing output to a file via fixed name, and they should clobber. Theirs definitely a bug here as your commit mentions, but lets fix that bug and correct the doc.

**Comment by jetwhiz** [comment]
Hi @williamcroberts, 

I agree about the tool clobbering existing files, to keep it in line with how the other tools behave.  Should I update this PR just to remove the `ctx.out_file_path`-specific issues, without adding the fixed name fix-ups to `ctx.ctx_obj.path` (and update the documentation), or does this need more discussion?

**Comment by williamcroberts** [comment]
Oh I didn't realize that generate and create name portion was part of it or I likely would have balked at it. I'm trying to think of popular commandline tools on linux that have similar behavior.

**Comment by joshuagl** [comment]
I can't think of a popular tool with similar behaviour, but overwriting a context file is an irksome way to shoot oneself in the foot. If we are going to change the behaviour I think we should probably default to requiring a filename be passed for the context file (rather than having that argument be optional) as more required options seems friendlier than unexpected behaviour. What do you think?

**Comment by williamcroberts** [comment]
> I can't think of a popular tool with similar behaviour, but overwriting a context file is an irksome way to shoot oneself in the foot. If we are going to change the behaviour I think we should probably default to requiring a filename be passed for the context file (rather than having that argument be optional) as more required options seems friendlier than unexpected behaviour. What do you think?

I agree, the context file would become a mandatory option so you can't shoot yourself in the foot.

**Comment by jetwhiz** [comment]
Should I update this PR to make providing a context option mandatory and fix the issue involving the ctx.out_file_path?

**Comment by martinezjavier** [comment]
> I agree, the context file would become a mandatory option so you can't shoot yourself in the foot.

agree with this as well.

**Comment by martinezjavier** [comment]
> Should I update this PR to make providing a context option mandatory and fix the issue involving the ctx.out_file_path?

I think your fix is correct. We can make the option to be mandatory and explicit in a follow-up patch, since that's really independent of your fix.

**Pull request merged**
