### PR TITLE
Backport tpm2_flushcontext to 3.X

### PR DESCRIPTION
**Pull request by AndreasFuchsSIT**
Not the whole program was backported, because of the ESYS-SAPI conversion. Only flushing of all handles of a group and a particular handle are supported in this.

And since I'm completely unbeknown to the old SAPI conventions, please give this a deep review. Hope it works ok for addition.

Fixes: #1452

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
Updated, since the system-test was disfunctional

**Comment by williamcroberts** [comment]
Why didn't you just check out the project pre-esapi flip and backport that version?

**Comment by AndreasFuchsSIT** [comment]
There was one before ESAPI ? :-(

**Comment by williamcroberts** [comment]
> There was one before ESAPI ? :-(

git co cf768cdf9786

**Comment by williamcroberts** [comment]
where co is checkout

**Comment by AndreasFuchsSIT** [comment]
Does the approval mean you'll merge it, or should I do it next week, or do you ?

**Comment by williamcroberts** [comment]
> Does the approval mean you'll merge it, or should I do it next week, or do you ?

Ill merge it.

**Pull request merged**
