### PR TITLE
OpenSSL Format and getpubak/ek renames

### PR DESCRIPTION
**Pull request by williamcroberts**
Since we are going to a major version bump, and tpm2_getpubak and tpm2_getpubek had horrendous names that caused confusion, rename them to tpm2_createak and tpm2_createek respectively.

Change the -f option to -p, and use -f for specifying the format of the generated public key.

Fixes: #901
Fixes: #421

The session issues are on #917

### CODE REVIEW

**Comment by williamcroberts** [comment]
Nice catch @liuqun I will make sure to update that.

**Comment by williamcroberts** [comment]
@martinezjavier - Session handling, yet again, has reared it's ugly head. So some tools, and potential future tools, may need multiple sessions for auth. For instance tpm2_getpubak (tpm2_createak on this PR) needs multiple auths as indicated by the "password" options.

I'm thinking that the initial process of `-S` for session handle is a bit naive and limited. Perhaps, we use the existing password options and do something like `--password=session:path/to/session.dat`

This has a few effects:
1. Less options, at the expense of expanding the password mini-language
2. Works with existing tool options, no need to add new ones
3. Supports compound tools.

Thoughts?

**Comment by martinezjavier** [comment]
@williamcroberts I'll need to spend some time reading the docs again to fully grasp the issue and the possible solutions (it seems authorization and sessions is something I keep forgetting the details). But here are some thoughts.

IIUC you want to use the same option for password, HMAC and policy sessions, right? Then I think it shouldn't be called `password` but `authorization`.

By multiple you mean that it may require different authorization methods or that should support more than one? In other words, it should be an exclusive or or an either? AFAICT the TPM2 spec supports the latter, so I think the tools should do the same. With your suggested approach, would we have something like:

```
--password=session:path/to/session.dat,hmac:secretpassword
```

Or how do you plan to support multiple authorization methods?

If possible I also prefer to keep parsing at a minimum. Even if our format is simple, parsing strings in C is very error prone. So I wonder if wouldn't be better to just keep different `-p` and `-S` options for password and sessions and let getopt to do the parsing for us.

**Comment by williamcroberts** [comment]
@martinezjavier 
With respect to parsing,  the code already parses passwords. For example `-P"hex:abcd"`. So this would just be -P"session:session.dat"

With respect to why, tpm2_getpubak is a good example. It requires an owner and endorsement authorizations, so a single session option, like `-S` won't work as is. Either we would need:
1. More options
2. Smarten-up -S to have a map to the object, `-S"owner=owner.dat:hierarchy=hrchy.dat"`
3. Smarten up the existing "password" options
  1. Optionally rename them to authorization. I'm trying to keep non-backwards compat changes to a 
      minimum. 

I am leaning towards 3.

As far as using multiple methods for authorization, complex auths require a session AFAIK. The auth structure, TPMS_AUTH_COMMAND one sets the session handle to either:
1.  A valid session handle from create_session
2. TPM2_RS_PW (for password/hmac auth)

**Comment by martinezjavier** [comment]
> With respect to parsing, the code already parses passwords. For example -P"hex:abcd". So this would just be -P"session:session.dat"

I don't mind to extend the command, but still I think it should not be called `password`, since as you said the structure is TPMS_AUTH_COMMAND and is the authorization in the session are of the command.

Backward incompatible change wouldn't be an issue, we already broke a lot of things and are even changing the tool names for these.

**Pull request merged**
