### PR TITLE
Generate partial X.509 certificate using own struct

### PR DESCRIPTION
**Pull request by gotthardp**
The `tpm2_certifyX509certutil.c`:`generate_partial_X509()` creates a partial (in fact, an incomplete) certificate, see Part 3, 18.8.1. The OpenSSL team decided that starting from 3.0 the i2d should not create invalid encodings, so we need to create an own ASN.1 structure for this.

This PR:
 * Switches from `X509 *` to `TPM2_PARTIAL_CERT *`, which is adapted from https://github.com/openssl/openssl/issues/16257#issuecomment-895448370.
 * Removes unnecessary `X509_get_XX` - `X509_set_XX` pairs. (The pointer was retrieved and then put back, which is not necessary as the pointer was already set when retrieved.)
 * Removes the `fixup_cert` which I believe is not necessary now.

Fixes: #2813

### CODE REVIEW

**Comment by gotthardp** [comment]
I do *not* have a way to verify the output certificate is correct.

**Comment by williamcroberts** [comment]
> I do _not_ have a way to verify the output certificate is correct.

I guess we could create the TPM2_CertifyX509 command line tool and pass this into it?

**Comment by williamcroberts** [comment]
> > I do _not_ have a way to verify the output certificate is correct.
> 
> I guess we could create the TPM2_CertifyX509 command line tool and pass this into it?

So the tpm2-tss project has a test in test/integration/esys-certifyX509.int.c that takes the output of this tool and adds it as a included byte buffer, you could paste the output and test it.

**Comment by gotthardp** [comment]
> So the tpm2-tss project has a test in test/integration/esys-certifyX509.int.c that takes the output of this tool and adds it as a included byte buffer, you could paste the output and test it.

That `test/integration/esys-certifyX509.int` (`Esys_CertifyX509`) test passed with the "new" data. Of course, the `openssl asn1parse -in partial_cert.der -inform DER` happily prints the cert content, so it seems to be valid.

**Comment by williamcroberts** [comment]
That sounds good enough until we actually get a tool in place, I can add this tool. @idesai sound good to you?

**Pull request merged**
