### PR TITLE
fapi: add integration tests for policy or.

### PR DESCRIPTION
**Pull request by JuergenReppSIT**
* A test with different policies in or branches was added.
* A test with two nested or policies was added.

Signed-off-by: Juergen Repp <juergen.repp@sit.fraunhofer.de>

### CODE REVIEW

**Comment by JuergenReppSIT** [comment]
All travis test case should work after PR 1835 of tpm2-tss is merged.

**Comment by AndreasFuchsSIT** [comment]
@idesai This fails because tests run against 2.4.2.
Would it make sense to run CI against 2.4.x branch so we always get latest ?

**Comment by idesai** [comment]
> @idesai This fails because tests run against 2.4.2.
> 
> Would it make sense to run CI against 2.4.x branch so we always get latest ?

SGTM as long as a corresponding tpm2-tss release is cut from the .X branch close to the next tools release.

**Comment by idesai** [comment]
@JuergenReppSIT @AndreasFuchsSIT I have a PR to update to tpm2-tss v3.0.1 and tpm2-abrmd v2.3.3, are these changes compatible?

**Pull request merged**
