### PR TITLE
feat: support sm4 algorithms.

### PR DESCRIPTION
**Pull request by ymj-uos**
Signed-off-by: 杨明君 <yangmingjun@uniontech.com>

### CODE REVIEW

**Comment by ymj-uos** [comment]
企业微信截图_1641977399436

fix a compile error！
@idesai

**Comment by idesai** [comment]
@ymj-uos this looks, can you please rebase on PR https://github.com/tpm2-software/tpm2-tools/pull/2905

**Comment by idesai** [comment]
@ymj-uos, can you please rebase on to current master?

**Comment by ymj-uos** [comment]
https://github.com/tpm2-software/tpm2-tools/pull/2919

**Comment by ymj-uos** [comment]
ymj-uos:master

**Comment by ymj-uos** [comment]
Hi, I have rebase to new master branch, and check SM4 algorithm, all results are correct, except the CLang compile error!
I have upload a new PR for this. @idesai

**Pull request closed without merging**
