### PR TITLE
set umask to 0117 (drop owner execute, group execute and all for other)

### PR DESCRIPTION
**Pull request by williamcroberts**
Don't create world readable files.... make them only group readable and fully controllable by owner.

### CODE REVIEW

**Comment by idesai** [comment]
@williamcroberts for file permission 0640, umask = 027, right?

**Comment by williamcroberts** [comment]
> @williamcroberts for file permission 0640, umask = 027, right?

huh? It sets the default mask for open and creat. So this way the default for things like fopen will be a fie that is user readable/writeable, group readable, others no access.

**Comment by idesai** [comment]
> > @williamcroberts for file permission 0640, umask = 027, right?
> 
> huh? It sets the default mask for open and creat. So this way the default for things like fopen will be a fie that is user readable/writeable, group readable, others no access.

https://www.webune.com/forums/umask-calculator.html

**Comment by williamcroberts** [comment]
> > > @williamcroberts for file permission 0640, umask = 027, right?
> > 
> > 
> > huh? It sets the default mask for open and creat. So this way the default for things like fopen will be a fie that is user readable/writeable, group readable, others no access.
> 
> https://www.webune.com/forums/umask-calculator.html

Oh duh, "mask out the bits".... <facepalm>

**Comment by williamcroberts** [comment]
Oh boy, fapi stores things globaly, this might not be the proper umask. @AndreasFuchsSIT what would be a good umask for tss2 tools?

**Comment by diabonas** [comment]
Regarding FAPI, files under `/var/lib/tpm2-tss/system/keystore` should be group read-writable, see https://github.com/tpm2-software/tpm2-tss/issues/1810.

**Comment by williamcroberts** [comment]
> Regarding FAPI, files under `/var/lib/tpm2-tss/system/keystore` should be group read-writable, see [tpm2-software/tpm2-tss#1810](https://github.com/tpm2-software/tpm2-tss/issues/1810).

Will update to 0117

**Comment by williamcroberts** [comment]
Test program:
```C
#include <stdio.h>

#include <unistd.h>

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

int main() {

        umask(0117);

        int fd = open("foo.bar", O_CREAT, 0777);
        printf("fd: %d\n", fd);
        close(fd);

        return 0;
}
```
```bash
ls -la foo.bar 
-rw-rw---- 1 wcrobert wcrobert 0 Jul 30 15:03 foo.bar
```

**Comment by williamcroberts** [comment]
Oh darn we only wanted this for tss2_ tools, but I think it applies to tpm2_ tools as well. You may wish to create things a group can get to and use.

**Pull request merged**
