### PR TITLE
tools/tpm2_readpublic: Add option -n for saving object name

### PR DESCRIPTION
**Pull request by leeehui**
man/tpm2_readpublic.1.md: add description for option -n

Signed-off-by: Hui Li <leehui_hrbeu71102@163.com>

### CODE REVIEW

**Comment by leeehui** [comment]
I triggered build at tpm2-software/tpm2-tools/master c66e4f069b04dcb13caed1f6408e4d199e6cf925 on travis CI manually, the result is same as in this PR:

group: object:
	tools: ['tpm2_makecredential', 'tpm2_load', 'tpm2_unseal', 'tpm2_readpublic', 'tpm2_changeauth', 'tpm2_activatecredential', 'tpm2_createprimary', 'tpm2_loadexternal', 'tpm2_create']
	conflicts: set(['format', 'f'])
The command "./.ci/travis.run" exited with 1.


any idea?

**Comment by diabonas** [comment]
The option conflict referred to in the error message already existed before this PR, but wasn't detected correctly due to a bug. #1334 contains a fix, so rebasing this PR after #1334 is merged should cause the CI build to pass.

**Comment by leeehui** [comment]
@diabonas 
I'm newcomer on pr process
should I close this pr and wait for #1334 is merged, then rebase on my forked repo, ends with a new pr?
thanks

**Comment by leeehui** [comment]
I just found my newly add tool tpm2_policyduplicationselect(bf96408) has more conflicts with the "option conventions", so I will close this pr. After your pr is merged, I'd like to open a new one.
BTW, is there any docs about "option conventions"?

**Comment by diabonas** [comment]
@leeehui You can reuse the PR if you want by reopening it and doing `git pull --rebase https://github.com/tpm2-software/tpm2-tools.git` to fetch the latest changes from this repository and rebasing your work on top of it. After that, you need to force-push (`git push --force`) your changes to the forked repository because you are rewriting history (which you usually shouldn't do, but is ok for pull requests).

Regarding the option conventions, @williamcroberts is the expert. I don't think there is any formal documentation yet, but I think the basic principles are
- name the options consistent with other tools, try to reuse names if appropriate.
- [upper-case short options refer to the parent object, lower-case short options refer to the current object](https://github.com/tpm2-software/tpm2-tools/pull/1334#discussion_r262128427).

That being said, IMHO your newly introduced options look fine and can probably be added to the ignore list of the option analyser.

**Comment by williamcroberts** [comment]
@leeehui no doc on option conventions I need to add one as we march forward on master.

In general the goal is:
* Consistent options within tool groups (tools are organized by the command spec)
* Consistent options amongst all tools where possible
* Capital options indicate parent object options
* Drop direct PCR policy options in tools that have it (tpm2_nvread) and use an auth mini-language to support.
    * Not adding more policy support in tools, use tpm2_startauthsession, tpm2_policyxxx commands.

**Pull request closed without merging**
