### PR TITLE
Policyticket

### LINKED ISSUE #869: Implement policyticket
Implement a tool to use the policyticket command.

### PR DESCRIPTION
**Pull request by idesai**
Fixes #869

### CODE REVIEW

**Comment by idesai** [comment]
@tstruk , @diabonas What does this error really mean ?
**"checking for suffix of executables... 
1143checking whether we are cross compiling... configure: error: in `/workspace/tpm2-tools/build':
1144configure: error: cannot run C compiled programs."**

The full log is [here](https://travis-ci.org/tpm2-software/tpm2-tools/jobs/594778726)

**Comment by tstruk** [comment]
@idesai I think this might be the source of the problem: "https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support"

**Comment by pdxjohnny** [comment]
It's failing for me too when I tried locally

```console
$ DOCKER_TAG=fedora-30 CC=clang ./.ci/travis.run
... from config.log ...
configure:2832: clang -o conftest -O1 -g -fsanitize=address -fno-omit-frame-pointer -g   conftest.c  >&5                                                                                                   [235/1854]
configure:2836: $? = 0
configure:2843: ./conftest
==29927==AddressSanitizer: libc interceptors initialized
|| `[0x10007fff8000, 0x7fffffffffff]` || HighMem    ||
|| `[0x02008fff7000, 0x10007fff7fff]` || HighShadow ||
|| `[0x00008fff7000, 0x02008fff6fff]` || ShadowGap  ||
|| `[0x00007fff8000, 0x00008fff6fff]` || LowShadow  ||
|| `[0x000000000000, 0x00007fff7fff]` || LowMem     ||
MemToShadow(shadow): 0x00008fff7000 0x000091ff6dff 0x004091ff6e00 0x02008fff6fff
redzone=16
max_redzone=2048
quarantine_size_mb=256M
thread_local_quarantine_size_kb=1024K
malloc_context_size=30
SHADOW_SCALE: 3
SHADOW_GRANULARITY: 8
SHADOW_OFFSET: 0x7fff8000
==29927==Installed the sigaction for signal 11
==29927==Installed the sigaction for signal 7
==29927==Installed the sigaction for signal 8
==29927==T0: stack [0x7ffce3310000,0x7ffce3b10000) size 0x800000; local=0x7ffce3b0da2c
==29927==AddressSanitizer Init done
==29928==Could not attach to thread 29927 (errno 1).
==29928==Failed suspending threads.
==29927==LeakSanitizer has encountered a fatal error.
==29927==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==29927==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
configure:2847: $? = 1
configure:2854: error: in `/workspace/tpm2-tools/build':
configure:2856: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

**Comment by pdxjohnny** [comment]
I think this is the solution:

```diff
diff --git a/.ci/travis.run b/.ci/travis.run
index 67c5d812..7e9dc03b 100755
--- a/.ci/travis.run
+++ b/.ci/travis.run
@@ -16,6 +16,7 @@ if [ "$TRAVIS_BRANCH" != "coverity_scan" ]; then
   # Do normal CI script
   ci_env=$(bash <(curl -s https://codecov.io/env))
   docker run $ci_env --env-file .ci/docker.env \
+    --security-opt seccomp=unconfined \
     -v "$(pwd):/workspace/tpm2-tools" "tpm2software/tpm2-tss:$DOCKER_TAG" \
     /bin/bash -c '/workspace/tpm2-tools/.ci/docker.run'

```

However: now we're missing file and something else is wrong:

```log
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
../configure: line 5781: /usr/bin/file: No such file or directory
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... clang -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if clang supports -fno-rtti -fno-exceptions... yes
checking for clang option to produce PIC... -fPIC -DPIC
checking if clang PIC flag -fPIC -DPIC works... yes
checking if clang static flag -static works... no
checking if clang supports -c -o file.o... yes
checking if clang supports -c -o file.o... (cached) yes
checking whether the clang linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
configure: error: source directory already configured; run "make distclean" there first
```

**Comment by pdxjohnny** [comment]
Ya, seccomp was the issue.

**Comment by idesai** [comment]
> Ya, seccomp was the issue for me locally, tested in travis: https://travis-ci.com/pdxjohnny/tpm2-tools/builds/131003686. Looks like that fixes it, PR in #1772

@pdxjohnny , Thanks!

**Pull request merged**
