### PR TITLE
feat: support sm4 algorithms.

### PR DESCRIPTION
**Pull request by ymj-uos**
Signed-off-by: 杨明君 <yangmingjun@uniontech.com>

### CODE REVIEW

**Comment by ymj-uos** [comment]
rm -v -f -r temp/

mkdir temp

cd temp

export TPM2TOOLS_TCTI=device:/dev/tpm0

tpm2 flushcontext -T device:/dev/tpm0 -t
tpm2 flushcontext -T device:/dev/tpm0 -l
tpm2 flushcontext -T device:/dev/tpm0 -s

iv_value=00000000000000000000000000000000
key_value=0123456789abcdeffedcba9876543210

echo -n "00000000000000000000000000000000" | xxd -r -ps > iv.bin
echo -n "0123456789abcdeffedcba9876543210" | xxd -r -ps > key.bin
echo -n "0123456789abcdeffedcba9876543210" | xxd -r -ps > plaintext.bin

tpm2 loadexternal -G sm4 -r key.bin -n name.bin -c key.ctx > stdout.yaml

tpm2 encryptdecrypt -T device:/dev/tpm0 -c key.ctx --iv=iv.bin -o plaintext.bin.enc.tpm2 plaintext.bin
xxd -g 4 -c 32 plaintext.bin.enc.tpm2

openssl enc -sm4-cfb -d -p -v -nosalt \
            -iv $iv_value \
            -K $key_value \
            -in plaintext.bin.enc.tpm2 \
            -out plaintext.bin.dec.ossl
xxd -g 4 -c 32 plaintext.bin.dec.ossl

openssl enc -sm4-cfb -e -p -v -nosalt \
            -iv $iv_value \
            -K $key_value \
            -in plaintext.bin \
            -out plaintext.bin.enc.ossl
xxd -g 4 -c 32 plaintext.bin.enc.ossl

tpm2 flushcontext -T device:/dev/tpm0 -t
tpm2 encryptdecrypt -T device:/dev/tpm0 -d -c key.ctx --iv=iv.bin -o plaintext.bin.dec.tpm2 plaintext.bin.enc.ossl
xxd -g 4 -c 32 plaintext.bin.dec.tpm2

chmod a+r -R .
chown uos:uos -R .

ls -l
exit 0

**Comment by ymj-uos** [comment]
I use this script to check the result of TPM calculate. all of which are correct.

**Comment by ymj-uos** [comment]
@idesai

**Comment by idesai** [comment]
@ymj-uos thank you for the PR. Most of the proposed changes are similar to a previous PR #2905. I will merge that first to see any differences in your PR.

I like that you have tested the changes. Unfortunately, I do not have a TPM with SM algorithms. After I merge this PR and 2905, may I request you to please test the master branch?

**Comment by ymj-uos** [comment]
@idesai I'd be very glad to complete these tests of master branch for you.

**Comment by ymj-uos** [comment]
Recently, I am studying SM algorithms parts of TPM, I will upload more PRs about SM2/SM3/SM4. I want to make SM Algorithms parts of TPM TSS2 perfect.

**Comment by idesai** [comment]
@ymj-uos can you please the dump of `tpm2_getcap pcrs` from the TPM with SM algs?

**Comment by ymj-uos** [comment]
image
@idesai

**Comment by ymj-uos** [comment]
企业微信截图_1641977399436

**Pull request closed without merging**
