### PR TITLE
Auth input: Check for NULL termination

### PR DESCRIPTION
**Pull request by AndreasFuchsTPM**
When reading auths from a file, add a check that they are NULL terminated.

### CODE REVIEW

**Review by JuergenReppSIT — CHANGES_REQUESTED** [review]
Here it's possible that if the password is read from the file that there is no \0 char at the end of the buffer. It would be better to reallocate the buffer with size+1 after  files_load_bytes_from_buffer_or_file_or_stdin and add the \0.

**Comment by AndreasFuchsTPM** [comment]
> Here it's possible that if the password is read from the file that there is no \0 char at the end of the buffer. It would be better to reallocate the buffer with size+1 after files_load_bytes_from_buffer_or_file_or_stdin and add the \0.

You mean like this ?

**Comment by JuergenReppSIT** [comment]
> > Here it's possible that if the password is read from the file that there is no \0 char at the end of the buffer. It would be better to reallocate the buffer with size+1 after files_load_bytes_from_buffer_or_file_or_stdin and add the \0.
> 
> You mean like this ?

Yes, but I think the coverity error is a false positive. Now I saw: the buffer is already allocated with calloc an the size passed do `files_load_bytes_from_buffer_or_file_or_stdin` is decremented. So I would say we can close this PR. No change is needed.

**Comment by AndreasFuchsTPM** [comment]
> > > Here it's possible that if the password is read from the file that there is no \0 char at the end of the buffer. It would be better to reallocate the buffer with size+1 after files_load_bytes_from_buffer_or_file_or_stdin and add the \0.
> > 
> > 
> > You mean like this ?
> 
> Yes, but I think the coverity error is a false positive. Now I saw: the buffer is already allocated with calloc an the size passed do `files_load_bytes_from_buffer_or_file_or_stdin` is decremented. So I would say we can close this PR. No change is needed.

Oh yes, I see this now.
However, calloc does not guarantee \0 initialization. So I guess the line `buffer[size-1] = '\0';` should stay, right ?

**Review by JuergenReppSIT — APPROVED** [review]

**Pull request merged**
