### PR TITLE
Add FAPI support to all tpm2_* tools

### PR DESCRIPTION
**Pull request by AndreasFuchsTPM**
By introducing a "tss2:" prefix to denote a FAPI object.

Open would be the Question
- Should the FAPI-calling be encapsulated in a different file than object.c ?
- Should we get the TCTI from the FAPI context or do we want to allow ppl to use FAPI-context objects in the regular tcti context ?

### CODE REVIEW

**Comment by williamcroberts** [comment]
> By introducing a "tss2:" prefix to denote a FAPI object.
> 
> Open would be the Question
> 
> * Should the FAPI-calling be encapsulated in a different file than object.c ?

Yes I think that. Just handle it in the normal code flows that exist.

> * Should we get the TCTI from the FAPI context or do we want to allow ppl to use FAPI-context objects in the regular tcti context ?

I would say get the FAPI TCTI, but we would then need to make sure that if --tcti is set, we error out or at least say we ignore it in a warning.

**Comment by AndreasFuchsSIT** [comment]
> > * Should we get the TCTI from the FAPI context or do we want to allow ppl to use FAPI-context objects in the regular tcti context ?
> 
> I would say get the FAPI TCTI, but we would then need to make sure that if --tcti is set, we error out or at least say we ignore it in a warning.

I thought about this some more and if we get the FAPI TCTI we run into problems with session usage, since StartAuthSession does not take a FAPI object. So we'd either need to add a flag there as well or just not allow session support when using FAPI objects.
Hmpf... :-(

**Comment by AndreasFuchsSIT** [comment]
I'll close this for now, due to lack of time to work on this and I don't want to keep the PR tab cluttered much longer

**Comment by williamcroberts** [comment]
> I'll close this for now, due to lack of time to work on this and I don't want to keep the PR tab cluttered much longer

Thanks I'm a zero-inboxer, open things in lists give me anxiety :-p

**Pull request closed without merging**
