### PR TITLE
Add ccache to speed up travis runs.

### PR DESCRIPTION
**Pull request by DomiNic5787**
see [https://github.com/tpm2-software/tpm2-tss/pull/1403](https://github.com/tpm2-software/tpm2-tss/pull/1403)

Signed-off-by: Dominic Grauvogl <dominicmanuel.grauvogl@infineon.com>

### CODE REVIEW

**Comment by diabonas** [comment]
Not sure whether that works here, since the software is built in a Docker container, so the ccache directory will also live there. I guess you would need to add ccache to the Dockerfile and bind mount `$HOME/.ccache` from the Travis container to the container.

**Comment by williamcroberts** [comment]
> Not sure whether that works here, since the software is built in a Docker container, so the ccache directory will also live there. I guess you would need to add ccache to the Dockerfile and bind mount `$HOME/.ccache` from the Travis container to the container.

If it's inside the container won't it still use $HOME/.ccache which would be the containers version, where $HOME is /root?

**Comment by diabonas** [comment]
As far as I can see, the Travis build directory [is mounted to `/workspace/tpm2-tools` in the container](https://github.com/tpm2-software/tpm2-tools/blob/c4367da5d502c0abe66f27ecf190168a63f66472/.ci/travis.run#L51), so everything in the build directory is visible to Travis. Everything else in the container is not retained, so the container `/root/.ccache` is lost when Travis tries to upload the cache after the build (from its own `$HOME/.ccache`). Anyway, the Docker container doesn't know about ccache since Travis only adds [`/usr/lib/ccache` to `$PATH`](https://docs.travis-ci.com/user/caching/#ccache-cache), but this isn't propagated to the container.

**Comment by williamcroberts** [comment]
@diabonas I get what you mean now, I was thinking inside the container. Yeah the ccache would be gone and not visible to travis.

**Pull request closed without merging**
