### PR TITLE
Fixes for upcoming 3.0.5 release

### PR DESCRIPTION
**Pull request by martinezjavier**
This pull-request contains a couple of fixes from the 3.X branch that should make to the 3.0.X branch. These will be included in an upcoming 3.0.5 release.

### CODE REVIEW

**Comment by joshuagl** [comment]
LGTM

**Comment by martinezjavier** [comment]
@williamcroberts as a heads up since I had a conversation with @joshuagl over IRC. Before merging this we should probably document what's the process for changing the `CHANGELOG.md` and tagging release candidates. We haven't been consistent in this regard on the different major releases / branches.

I've proposed the following but I'll create a PR against `RELEASE.md` probably tomorrow:

*  When cutting a -rc, add a new entry to the CHANGELOG that has the first release candidate version (i.e: 3.0.5-rc0) and a date. The date is important so people checking out a -rc tag or downloading a distributed tarball can have a sane CHANGELOG. This entry will have all the delta between the latest release and the first release candate -rc0.
* For every release candidate, append all the delta to the entry and replace -rcN - 1 with -rcN and update the date. The commit for this change will be tagged as $version-rcN.
* For a final release, change the version to the final release version (i.e: 3.0.5-rc3 -> 3.0.5) and update the date. The commit for this change will be tagged as $version.

@joshuagl please let me know if I missed anything from your suggestions.

**Comment by williamcroberts** [comment]
Seems reasonable, want to make a change to the RELEASE.md?

**Comment by martinezjavier** [comment]
@williamcroberts sure thing, I'll propose a PR tomorrow. Thanks!

**Pull request merged**
