### PR TITLE
tpm2_eventlog: fix missing space for secureboot

### LINKED ISSUE #2334: Missing space in YAML output for value of SecureBoot
Note that there is no trailing space in https://github.com/tpm2-software/tpm2-tools/blob/daa952a661581b0fcaaff36d5314b40b3b6f8d48/lib/tpm2_eventlog_yaml.c#L348 and no leading space in the subsequent output statements.  Thus we get invalid YAML like the following.

```
      UnicodeName: SecureBoot
      VariableData:
        Enabled:'Yes'
```

### PR DESCRIPTION
**Pull request by huang195**
Fixes #2334

### CODE REVIEW

**Comment by huang195** [comment]
Looks like these 2 tests are failing
```
FAIL: test/integration/tests/load.sh
FAIL: test/integration/tests/flushcontext.sh
```
@williamcroberts @idesai I don't think this PR is impacting these tests in any way, but I could be wrong.

**Comment by idesai** [comment]
> Looks like these 2 tests are failing
> 
> ```
> FAIL: test/integration/tests/load.sh
> FAIL: test/integration/tests/flushcontext.sh
> ```
> 
> @williamcroberts @idesai I don't think this PR is impacting these tests in any way, but I could be wrong.

re-running >>>

**Comment by huang195** [comment]
@idesai I force pushed it once to retrigger CI, but it failed with the same error.

**Comment by idesai** [comment]
> @idesai I force pushed it once to retrigger CI, but it failed with the same error.

Looks good now :)

**Comment by huang195** [comment]
@idesai ah nice, must be a fluke!

**Pull request merged**
